spring:
  application:
    name: apitest

  datasource:
    url: jdbc:postgresql://localhost:5432/ssotest
    username: ssodev
    password: ${DbPasswork:sso2022ok}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /apitest

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html